define([], function() {
'use strict';
return {
    root: {
        BUTTONS:{
            INSTALL_APPS:'Install apk',
            SELECT_ALL:'Select all',
            DESELECT_ALL:'Deselect all',
            UNINSTALL:'Uninstall',
            REINSTALL:'Reinstall',
            COMPLETE:'Complete'
        },
        CONFIRMS:{
            INSTALL:'Confirm install on your phone.',
            UNINSTALL:'Confirm uninstall on your phone.',
            UNKNOWNTIPS:'Installation tips',
            INSTALL_COMPLETE:'Installation complete'
        },
        NOAPP:'No applications on your phone.',
        UPGRADE_TIP:'Please Update SnapPea.',
        DEL_ONE_APP:{
            TITLE:'Uninstall application',
            CONTENT:'Uninstall the selected application from your phone?',
            AGREE:'Uninstall',
            CANCEL:'Cancel'
        },
        DEL_MORE_APPS:{
            TITLE:'Uninstall applications',
            CONTENT:'Uninstall the selected applications from your phone?',
            AGREE:'Uninstall',
            CANCEL:'Cancel'
        },
        WORDS:{
            SIZE:'Size',
            INSTALLATION:'Installation',
            VERSION:'Version',
            PERMISSIONS:'Permissions'
        },
        PERMISSIONS:{
            "android.permission.SEND_SMS": "send SMS messages",
            "android.permission.SEND_SMS_NO_CONFIRMATION": "send SMS messages with no confirmation",
            "android.permission.CALL_PHONE": "directly call phone numbers",
            "android.permission.RECEIVE_SMS": "receive text messages (SMS)",
            "android.permission.RECEIVE_MMS": "receive text messages (MMS)",
            "android.permission.RECEIVE_EMERGENCY_BROADCAST": "receive emergency broadcasts",
            "android.permission.READ_CELL_BROADCASTS": "read cell broadcast messages",
            "android.permission.READ_SMS": "read your text messages (SMS or MMS)",
            "android.permission.WRITE_SMS": "edit your text messages (SMS or MMS)",
            "android.permission.RECEIVE_WAP_PUSH": "receive text messages (WAP)",
            "android.permission.READ_CONTACTS": "read your contacts",
            "android.permission.WRITE_CONTACTS": "modify your contacts",
            "android.permission.READ_CALL_LOG": "read call log",
            "android.permission.WRITE_CALL_LOG": "write call log",
            "android.permission.READ_PROFILE": "read your own contact card",
            "android.permission.WRITE_PROFILE": "modify your own contact card",
            "android.permission.READ_SOCIAL_STREAM": "read your social stream",
            "android.permission.WRITE_SOCIAL_STREAM": "write to your social stream",
            "android.permission.READ_CALENDAR": "read calendar events plus confidential information",
            "android.permission.WRITE_CALENDAR": "add or modify calendar events and send email to guests without owners\\' knowledge",
            "android.permission.READ_USER_DICTIONARY": "read terms you added to the dictionary",
            "android.permission.WRITE_USER_DICTIONARY": "write to user-defined dictionary",
            "com.android.browser.permission.READ_HISTORY_BOOKMARKS": "read your Web bookmarks and history",
            "com.android.browser.permission.WRITE_HISTORY_BOOKMARKS": "write web bookmarks and history",
            "com.android.alarm.permission.SET_ALARM": "set an alarm",
            "com.android.voicemail.permission.ADD_VOICEMAIL": "add voicemail",
            "android.permission.ACCESS_FINE_LOCATION": "precise (GPS) location",
            "android.permission.ACCESS_COARSE_LOCATION": "approximate (network-based) location",
            "android.permission.ACCESS_MOCK_LOCATION": "mock location sources for testing",
            "android.permission.ACCESS_LOCATION_EXTRA_COMMANDS": "access extra location provider commands",
            "android.permission.INSTALL_LOCATION_PROVIDER": "permission to install a location provider",
            "android.permission.INTERNET": "full network access",
            "android.permission.ACCESS_NETWORK_STATE": "view network connections",
            "android.permission.ACCESS_WIFI_STATE": "view Wi-Fi connections",
            "android.permission.ACCESS_WIMAX_STATE": "View WiMAX connections",
            "android.permission.BLUETOOTH": "pair with Bluetooth devices",
            "android.permission.NFC": "control Near Field Communication",
            "android.permission.USE_SIP": "make/receive Internet calls",
            "android.permission.ACCOUNT_MANAGER": "act as the AccountManagerService",
            "android.permission.GET_ACCOUNTS": "find accounts on the device",
            "android.permission.AUTHENTICATE_ACCOUNTS": "create accounts and set passwords",
            "android.permission.USE_CREDENTIALS": "use accounts on the device",
            "android.permission.MANAGE_ACCOUNTS": "add or remove accounts",
            "android.permission.MODIFY_AUDIO_SETTINGS": "change your audio settings",
            "android.permission.RECORD_AUDIO": "record audio",
            "android.permission.CAMERA": "take pictures and videos",
            "android.permission.VIBRATE": "control vibration",
            "android.permission.FLASHLIGHT": "control flashlight",
            "android.permission.MANAGE_USB": "manage preferences and permissions for USB devices",
            "android.permission.ACCESS_MTP": "implement MTP protocol",
            "android.permission.HARDWARE_TEST": "test hardware",
            "android.permission.PROCESS_OUTGOING_CALLS": "reroute outgoing calls",
            "android.permission.MODIFY_PHONE_STATE": "modify phone state",
            "android.permission.READ_PHONE_STATE": "read phone status and identity",
            "android.permission.READ_EXTERNAL_STORAGE": "test access to protected storage",
            "android.permission.WRITE_EXTERNAL_STORAGE": "modify or delete the contents of your USB storage",
            "android.permission.WRITE_MEDIA_STORAGE": "modify/delete internal media storage contents",
            "android.permission.WRITE_SETTINGS": "modify system settings",
            "android.permission.WRITE_GSERVICES": "modify the Google services map",
            "android.permission.EXPAND_STATUS_BAR": "expand/collapse status bar",
            "android.permission.GET_TASKS": "retrieve running apps",
            "android.permission.GET_DETAILED_TASKS": "retrieve details of running apps",
            "android.permission.REORDER_TASKS": "reorder running apps",
            "android.permission.REMOVE_TASKS": "stop running apps",
            "android.permission.START_ANY_ACTIVITY": "start any activity",
            "android.permission.SET_SCREEN_COMPATIBILITY": "set screen compatibility",
            "android.permission.CHANGE_CONFIGURATION": "change system display settings",
            "android.permission.RESTART_PACKAGES": "close other apps",
            "android.permission.KILL_BACKGROUND_PROCESSES": "close other apps",
            "android.permission.FORCE_STOP_PACKAGES": "force stop other apps",
            "android.permission.RETRIEVE_WINDOW_CONTENT": "retrieve screen content",
            "android.permission.SYSTEM_ALERT_WINDOW": "draw over other apps",
            "android.permission.SET_ANIMATION_SCALE": "modify global animation speed",
            "android.permission.PERSISTENT_ACTIVITY": "make app always run",
            "android.permission.GET_PACKAGE_SIZE": "measure app storage space",
            "android.permission.SET_PREFERRED_APPLICATIONS": "set preferred apps",
            "android.permission.RECEIVE_BOOT_COMPLETED": "run at startup",
            "android.permission.BROADCAST_STICKY": "send sticky broadcast",
            "android.permission.WAKE_LOCK": "prevent tablet from sleeping",
            "android.permission.SET_WALLPAPER": "set wallpaper",
            "android.permission.SET_WALLPAPER_HINTS": "adjust your wallpaper size",
            "android.permission.SET_TIME": "set time",
            "android.permission.SET_TIME_ZONE": "set time zone",
            "android.permission.MOUNT_UNMOUNT_FILESYSTEMS": "access USB storage filesystem",
            "android.permission.MOUNT_FORMAT_FILESYSTEMS": "erase USB storage",
            "android.permission.ASEC_ACCESS": "get information on internal storage",
            "android.permission.ASEC_CREATE": "create internal storage",
            "android.permission.ASEC_DESTROY": "destroy internal storage",
            "android.permission.ASEC_MOUNT_UNMOUNT": "mount/unmount internal storage",
            "android.permission.ASEC_RENAME": "rename internal storage",
            "android.permission.DISABLE_KEYGUARD": "disable your screen lock",
            "android.permission.READ_SYNC_SETTINGS": "read sync settings",
            "android.permission.WRITE_SYNC_SETTINGS": "toggle sync on and off",
            "android.permission.READ_SYNC_STATS": "read sync statistics",
            "android.permission.WRITE_APN_SETTINGS": "change/intercept network settings and traffic",
            "android.permission.SUBSCRIBED_FEEDS_READ": "read subscribed feeds",
            "android.permission.SUBSCRIBED_FEEDS_WRITE": "write subscribed feeds",
            "android.permission.CHANGE_NETWORK_STATE": "change network connectivity",
            "android.permission.CHANGE_WIFI_STATE": "connect and disconnect from Wi-Fi",
            "android.permission.CHANGE_WIMAX_STATE": "Change WiMAX state",
            "android.permission.CHANGE_WIFI_MULTICAST_STATE": "allow Wi-Fi Multicast reception",
            "android.permission.BLUETOOTH_ADMIN": "access Bluetooth settings",
            "android.permission.CLEAR_APP_CACHE": "delete all app cache data",
            "android.permission.ALLOW_ANY_CODEC_FOR_PLAYBACK": "use any media decoder for playback",
            "android.permission.WRITE_SECURE_SETTINGS": "modify secure system settings",
            "android.permission.DUMP": "retrieve system internal state",
            "android.permission.READ_LOGS": "read sensitive log data",
            "android.permission.SET_DEBUG_APP": "enable app debugging",
            "android.permission.SET_PROCESS_LIMIT": "limit number of running processes",
            "android.permission.SET_ALWAYS_FINISH": "force background apps to close",
            "android.permission.SIGNAL_PERSISTENT_PROCESSES": "send Linux signals to apps",
            "android.permission.DIAGNOSTIC": "read/write to resources owned by diag",
            "android.permission.STATUS_BAR": "disable or modify status bar",
            "android.permission.STATUS_BAR_SERVICE": "status bar",
            "android.permission.FORCE_BACK": "force app to close",
            "android.permission.UPDATE_DEVICE_STATS": "modify battery statistics",
            "android.permission.INTERNAL_SYSTEM_WINDOW": "display unauthorized windows",
            "android.permission.MANAGE_APP_TOKENS": "manage app tokens",
            "android.permission.INJECT_EVENTS": "press keys and control buttons",
            "android.permission.SET_ACTIVITY_WATCHER": "monitor and control all app launching",
            "android.permission.SHUTDOWN": "partial shutdown",
            "android.permission.STOP_APP_SWITCHES": "prevent app switches",
            "android.permission.READ_INPUT_STATE": "record what you type and actions you take",
            "android.permission.BIND_INPUT_METHOD": "bind to an input method",
            "android.permission.BIND_ACCESSIBILITY_SERVICE": "bind to an accessibility service",
            "android.permission.BIND_TEXT_SERVICE": "bind to a text service",
            "android.permission.BIND_VPN_SERVICE": "bind to a VPN service",
            "android.permission.BIND_WALLPAPER": "bind to a wallpaper",
            "android.permission.BIND_DEVICE_ADMIN": "interact with a device admin",
            "android.permission.SET_ORIENTATION": "change screen orientation",
            "android.permission.SET_POINTER_SPEED": "change pointer speed",
            "android.permission.SET_KEYBOARD_LAYOUT": "change keyboard layout",
            "android.permission.INSTALL_PACKAGES": "directly install apps",
            "android.permission.CLEAR_APP_USER_DATA": "delete other apps\\' data",
            "android.permission.DELETE_CACHE_FILES": "delete other apps\\' caches",
            "android.permission.DELETE_PACKAGES": "delete apps",
            "android.permission.MOVE_PACKAGE": "move app resources",
            "android.permission.CHANGE_COMPONENT_ENABLED_STATE": "enable or disable app components",
            "android.permission.GRANT_REVOKE_PERMISSIONS": "grant or revoke permissions",
            "android.permission.ACCESS_SURFACE_FLINGER": "access SurfaceFlinger",
            "android.permission.READ_FRAME_BUFFER": "read frame buffer",
            "android.permission.BRICK": "permanently disable tablet",
            "android.permission.REBOOT": "force tablet reboot",
            "android.permission.DEVICE_POWER": "power tablet on or off",
            "android.permission.FACTORY_TEST": "run in factory test mode",
            "android.permission.BROADCAST_PACKAGE_REMOVED": "send package removed broadcast",
            "android.permission.BROADCAST_SMS": "send SMS-received broadcast",
            "android.permission.BROADCAST_WAP_PUSH": "send WAP-PUSH-received broadcast",
            "android.permission.MASTER_CLEAR": "reset system to factory defaults",
            "android.permission.CALL_PRIVILEGED": "directly call any phone numbers",
            "android.permission.PERFORM_CDMA_PROVISIONING": "directly start CDMA tablet setup",
            "android.permission.CONTROL_LOCATION_UPDATES": "control location update notifications",
            "android.permission.ACCESS_CHECKIN_PROPERTIES": "access checkin properties",
            "android.permission.PACKAGE_USAGE_STATS": "update component usage statistics",
            "android.permission.BATTERY_STATS": "modify battery statistics",
            "android.permission.BACKUP": "control system backup and restore",
            "android.permission.CONFIRM_FULL_BACKUP": "confirm a full backup or restore operation",
            "android.permission.BIND_REMOTEVIEWS": "bind to a widget service",
            "android.permission.BIND_APPWIDGET": "choose widgets",
            "android.permission.CHANGE_BACKGROUND_DATA_SETTING": "change background data usage setting",
            "android.permission.ACCESS_CACHE_FILESYSTEM": "access the cache filesystem",
            "android.permission.COPY_PROTECTED_DATA": "copy content",
            "android.permission.READ_NETWORK_USAGE_HISTORY": "read historical network usage",
            "android.permission.MANAGE_NETWORK_POLICY": "manage network policy",
            "android.permission.MODIFY_NETWORK_ACCOUNTING": "modify network usage accounting",
            "android.permission.PACKAGE_VERIFICATION_AGENT": "verify packages",
            "android.permission.BIND_PACKAGE_VERIFIER": "bind to a package verifier",
            "android.permission.SERIAL_PORT": "access serial ports",
            "android.permission.ACCESS_CONTENT_PROVIDERS_EXTERNALLY": "access content providers externally",
            "android.permission.UPDATE_LOCK": "discourage automatic device updates"
        }
    }
};
});
